### ISSUE TITLE
[HW2] 테스트 실행시 오류 질문드립니다

### ISSUE THREAD

**Issue by th-snu** [swsnu/swppfall2019#114]
FAIL  src/Components/Comment/Comment.test.js
  ● Test suite failed to run

    Cannot find module 'react' from 'index.js'

이런 오류가 뜨면서 테스트 실행 자체를 못하는데 실제 페이지 실행시엔 이런 오류가 발생이 안됩니다.
동시에 일부 테스트 코드는 이상 없이 실행이 됩니다

PASS  src/Components/Article/Article.test.js

테스트 코드와 대응 되는 스크립트랑 그렇게 상관 없어 보이는 파일에서 저런 오류가 뜨는데 혹시 원인 예상되는 것이 있을지 질문드립니다..

**Comment by ktaebum** [comment]
한 번 `index.js`를 상대경로 맞추어서 `./index.js`로 바꿔보시겠어요??

**Comment by th-snu** [comment]
문제가 되는 모듈들이 import하는건 store\actions\index.js인 것 같아서 일단 이걸 기준으로 말씀드리면
import * as actionCreators from './Stores/Actions/index';
import * as actionCreators from '../../Stores/Actions/index';
와 같이 상대경로로 import 하고 있네요. 혹시 다른 곳에서 경로를 말하시는 것이라면 어디에 있는 경로를 말하는 것인지 알려주실 수 있나요?

**Comment by mss8087** [comment]
저도 같은 에러가 발생하였었는데,
action을 테스트할 때 index에서 actionCreators를 불러오지않고,
해당 action이 정의된 파일에서 (예를들어 ./Store/Actions/articles) 직접 불러오면 잘 해결되었던 것 같습니다.

**Comment by hikizisa** [comment]
말해주신 방법으로는 해결이 안됐네요..
그런데 src 바로 아래의 index에서 store을 만들어둔걸 예시처럼 store.js를 따로 만들어두니 다른 종류의 오류로 바뀌었네요

**Comment by th-snu** [comment]
그렇게 실행해도 해결이 안되는것같네요..

**Comment by th-snu** [comment]
at Resolver.resolveModule (node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (../../../../node_modules/mini-create-react-context/dist/cjs/index.js:1:142)

오류 로그를 보니까 src의 index.js에서 일어난 문제는 아닌거같은데 처음 질문의 내용대로 검색해도 해결방법이 잘 안나오네요
