### ISSUE TITLE
[HW2] question about execution of skeleton code

### ISSUE THREAD

**Issue by jihoonrf** [swsnu/swppfall2019#54]
I cloned hw2 repo to my local and typed as README of hw2 said
```
> yarn install
> yarn run backend
```
But an error occurs like below
```
{ Error: watch api ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at start.then (/ (...) /node_modules/json-server/lib/cli/run.js:179:10)
    at <anonymous>
  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch api',
  filename: 'api' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I changed nothing about the codes or the directory.
What should I do?

**Comment by ktaebum** [comment]
Since `ENOSPC` denotes no space in device, could you check your device storage status?
If error still occurs, please let me know about your OS environment, Node version, and some other environ configurations

**Comment by jihoonrf** [comment]
I'm using ubuntu 18.04, Node v8.10.0, yarn 1.17.3, and npm 6.11.3.
Free space of disk is over 200GB, which is pretty enough I think..
Or does it matter that I'm using ubuntu by multi-booting with Windows10?

**Comment by ktaebum** [comment]
@Spiraline thanks! @jihoonrf could you try this solution?

**Comment by jihoonrf** [comment]
It works! Thank you very much :D
